version: "3"

services:
  tomcat:
    image: tomcat:8.5
    ports:
      - 8080:8080
    volumes:
      - ./resources/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./resources/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
    networks:
      - server
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    networks:
      - server
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: java_tomcat
      MYSQL_USER: java_tomcat
      MYSQL_PASSWORD: secret

volumes:
  data:

networks:
  server:
    driver: bridge
