version: "3"

services:
  tomcat:
    image: tomcat:8.5-alpine
    ports:
      - ${TOMCAT_PORT}:8080
    volumes:
      - ./config/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./config/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./config/mysql-connector-java-5.1.44-bin.jar:/usr/local/tomcat/lib/mysql-connector-java-5.1.44-bin.jar
    networks:
      - server
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - server
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:80
    networks:
      - server
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql

volumes:
  db_data:

networks:
  server:
    driver: bridge
